name: LilyPad-Connect
version: 1.13.2
description: LilyPad

author: LilyPad
website: http://www.lilypadmc.org/

load: STARTUP
loadbefore: [ProtocolLib, ProtocolSupport]
main: lilypad.bukkit.connect.ConnectPlugin
